# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Sro3vtH7X9FYu0rJIk06IIKQpAebuK4
"""

from flask import Flask, render_template, request
import jsonify
import requests
import pickle
import numpy as np
import sklearn
from sklearn.preprocessing import StandardScaler
app = Flask(__name__)
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

analyzer = SentimentIntensityAnalyzer()

@app.route('/',methods=['GET'])
def Home():
    return render_template('index.html')
    

standard_to = StandardScaler()
@app.route("/predict", methods=['POST'])
def predict():
    if request.method == 'POST':
        text = request.form['text']
        s=analyzer.polarity_scores(text)
        print(s)
        if s['pos']>s['neg']:
            print('Positive')
            return render_template('Positive.html',prediction_texts="Positive Tweet")
            
        else:
            print('Negative')
            return render_template('Negative.html',prediction_texts="Negative Tweet")
    else:
        return render_template('index.html')
        

if __name__=="__main__":
    app.run(debug=True)